sudo: required
services:
  - docker

before_install:
  - docker build -t amitaucs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amitaucs/react-test npm test


after_success:
  - docker build -t amitaucs/multi-client ./client
  - docker build -t amitaucs/multi-nginx ./nginx
  - docker build -t amitaucs/multi-server ./server
  - docker build -t amitaucs/multi-worker ./worker
  # Login Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push in docker hub
  - docker push amitaucs/multi-client
  - docker push amitaucs/multi-nginx
  - docker push amitaucs/multi-server
  - docker push amitaucs/multi-worker

#deploy:
 # provider: elasticbeanstalk
  #region: ap-south-1
  #app: multi-docker
  #env: MultiDocker-env
  #bucket_name: elasticbeanstalk-ap-south-1-045020874358
  #bucket_path: docker-multi
  #on:
   # branch: master
  #access_key_id:
   # secure: $AWS_ACCESS_KEY
  #secret_access_key:
   # secure: $AWS_SECRET_KEY

